(function($){

$.scf.behavior.add('LoginForm',{attach:function(el,options,jQ){if(!options||!options.currentChallenge)
return;el.login=function(){if(el.tagName!="FORM")
return;if(options.hashedStorage&&!options.usePwdHashing)
options.usePwdHashing=true;var pwdInput=jQ.find("input[type=password]").get(0);if(pwdInput==null)throw new Error(23555,'Pasword control not found');if(pwdInput.value.length==0)
return;var encryptOrHash=function(s){if(options.usePwdHashing){if(typeof(MD5)!="function")throw new Error(23556,'MD5 function not found');if(options.hashedStorage)
s=MD5(s).toUpperCase();return $.scf.convert.base64.encode(s+options.currentChallenge);}
else{var h=$.scf.convert.base64.encode(s+"__"+options.currentChallenge);return h;}}
var address=el.action,hash,passwd=pwdInput.value;if(address.indexOf("?")==-1)address+="?";else address+="&"
if(navigator.userAgent.indexOf("Mozilla/")==0&&(parseInt(navigator.appVersion)>=4)){if(passwd)hash=encryptOrHash(passwd);else hash="";var js=0,n=0;for(i=0;i<el.elements.length;i++){if(el.elements[i].tagName=="FIELDSET"||!el.elements[i].name)continue;if(el.elements[i].name.length<=0||el.elements[i].name.charAt(0)=="_")continue;if(n>0)address+="&";address+=el.elements[i].name;address+="=";if(el.elements[i]==pwdInput)
address+=hash;else if(el.elements[i].type=="checkbox"&&!el.elements[i].checked)
address+="";else if(el.elements[i].type=="radio"&&!el.elements[i].checked)
address+="";else if(el.elements[i].name==".js"){js=1;address+="1";}
else
address+=escape(el.elements[i].value);n++;}
address+="&.hash="+(options.usePwdHashing?"1":"0");if(js==0)
address+="&.js=1";address+="&.md5=1";setTimeout(function(){location.replace(address);},300);return false;}
return true;}
el.location=el.action;$(el).submit(function(){return el.login();})},detach:function(el){}});;(function(W,$){'use strict';$(function(){function getValue(right){var s="";right.find("option").each(function(){s+=$(this).attr("value")+" ";});return s.replace(/^\s*|\s*$/gm,'');}
function duallistUpdateForm(table,left,right,form)
{var s=getValue(right);left.data("currentValue",s);form.trigger("SetValue",{control:left,value:s});return true;}
function initValues(table,left,right,form){var s=getValue(right);table.val(s);table.prop("defaultValue",s);}
$("form.xforms-form").bind({XForms_Enrich:function(e){$("table.xforms-control.dual-list",e.args.data).each(function(){var table=$(this),ix=0,form=table.closest("form"),lists=table.find("select"),left=$(lists[0]),right=$(lists[1]);initValues(table,left,right,form);table.find("select, button").focus(function(){table.triggerHandler("focus");});table.find("select, button").blur(function(){table.triggerHandler("blur");});table.find("select").each(function(){var sel=$(this);sel.data("s-ix",ix);sel.dblclick(function(e){table.find(".buttons button").get($(this).data("s-ix")).click();});ix++;});left.data("set-value",function(value,isDefaultValue){if(!isDefaultValue){W.console.log("set-value called on "+left.attr('id')+" with value '"+value+"' (current: '"+left.data("currentValue")+"')");if(left.data("currentValue")===value){return true;}
if(value){var values=value.split(' ');right.find("option").each(function(){var key=$(this).attr("value");if(!$.inArray(key,values)===-1){$(this).remove().appendTo(left);}});left.find("option").each(function(){var key=$(this).attr("value");if($.inArray(key,values)!==-1){$(this).remove().appendTo(right);}});}}});table.find(".buttons button").click(function(evt){var s="",selected,ix;if($(this).hasClass("select")==1)
{ix=0;selected=$(lists[0]).find("option:selected")}
else if($(this).hasClass("deselect")==1)
{ix=1;selected=$(lists[1]).find("option:selected")}
else if($(this).hasClass("up")==1)
{ix=2;selected=$(lists[1]).find("option:selected")}
else if($(this).hasClass("down")==1)
{ix=3;selected=$(lists[1]).find("option:selected")}
if(ix==0||ix==1)
{if(selected.length){selected.remove().appendTo($(lists[Math.abs(ix-1)]));duallistUpdateForm(table,left,right,form);}}
else if(ix==2)
{if(selected.length){selected.each(function(){var listItem=$(this);var listItemPosition=$(lists[1]).find("option").index(listItem)+1;if(listItemPosition>1)
{listItem.insertBefore(listItem.prev());}});duallistUpdateForm(table,left,right,form);}}
else
{if(selected.length){$(selected.get().reverse()).each(function(){var listItem=$(this);var itemsCount=$(lists[1]).find("option").length;var listItemPosition=$(lists[1]).find("option").index(listItem)+1;if(listItemPosition!=itemsCount)
{listItem.insertAfter(listItem.next());}});duallistUpdateForm(table,left,right,form);}}
return false;});});}});});}
(window,jQuery));(function(W,$){W.console=W.console||{log:function(){}};$(function(){var x=jQuery.ajaxSettings.xhr();if(!x.upload||typeof(window.FormData)==="undefined"){return;}
$("html").addClass("ajax-file-upload");$("form.xforms-form").bind({XForms_Enrich:function(e){function AppendFile(input,data,file,name){if(input.data("maxfilesize")&&file.size>input.data("maxfilesize")){ModalMessage(input.closest("form"),input.data("file-too-large-message")||"File too large");return false;}
if(input.data("filetypes")){var filetypes=input.data("filetypes").split(";");var typeAllowed=false;for(var i=0;i<filetypes.length;i++){var tp=filetypes[i];if(tp[tp.length-1]=="*"){if(file.type.substr(0,tp.length-1)==tp.substr(0,tp.length-1)){typeAllowed=true;break;}}else{if(file.type==tp){typeAllowed=true;break;}}}
if(!typeAllowed){ModalMessage(input.closest("form"),input.data("type-not-allowed-message")||"File type not allowed");return false;}}
data.append(name,file);return true;}
function ModalMessage(form,message){if(!jQuery.xforms.raiseEvent(form,e.args.xfOpts,"ModalMessage",{data:message}))
alert(message);}
$("input[type=file].drag-drop",e.args.data).each(function(){var input=$(this),defaultText=input.data("default-text")||"Drop files here...",selectButtonText=input.data("button-text")||"Select file",form=input.closest("form"),dropArea=$('<label for=\"'+input.attr("id")+'\" class=\"btn icon_sys22 icon-sys22-media drag-drop-upload\">'+selectButtonText+'</label><div class="drag-drop-upload"><span>'+defaultText+'</span></div>');input.addClass("xforms-incremental");input.css({opacity:0,width:"absolute",position:"fixed",left:"-5000px"});input.after(dropArea);dropArea.find("span").bind({dragenter:function(evt){evt.stopPropagation();evt.preventDefault();$(this).addClass('over');},dragleave:function(evt){evt.stopPropagation();evt.preventDefault();$(this).removeClass('over');},drop:function(evt){evt.stopPropagation();evt.preventDefault();var maxuploads=input.hasClass("multiple")?input.data("maxuploads")||10:1;$(this).removeClass('over');var files=evt.originalEvent.dataTransfer.files;if(files.length>0){var data=new FormData();data.append('XForms-Context',e.args.xfOpts.state.guid);if(input.hasClass("multiple")){if(files.length>maxuploads){if(maxuploads==1)
ModalMessage(form,input.data("single-file-message")||"Only one file allowed");else
ModalMessage(form,(input.data("too-many-files-message")||"Only {0} files allowed").replace(/\{0\}/g,maxuploads));return;}
for(i=0;i<files.length;i++){var ctrlName=input.get(0).name+"__dd_"+i;if(!AppendFile(input,data,files[i],ctrlName))
return;}}else{if(files.length>1){ModalMessage(form,input.data("single-file-message")||"Only one file allowed");return;}
if(!AppendFile(input,data,files[0],input.get(0).name))
return;}
e.args.xfOpts.state.pendingUpload=true;$.ajax({type:"POST",url:form.attr("action"),contentType:false,processData:false,data:data,xhr:function(){var x=jQuery.ajaxSettings.xhr();if(x.upload){x.upload.addEventListener('progress',function(e){dropArea.find("span").html(parseInt((e.loaded/e.total)*100,0)+"%");},false);}
return x;},success:function(res){e.args.xfOpts.state.pendingUpload=false;dropArea.find("span").html(input.data("ready-message")||"Ready!").delay(1000).html(defaultText);input.prop("ddupload_completed",true);input.wrap('<form>').closest('form').get(0).reset();input.unwrap();input.change().blur();input.prop("ddupload_completed",null);},complete:function(res){e.args.xfOpts.state.pendingUpload=false;}});}}});});$(document).on('dragenter',function(e){e.stopPropagation();e.preventDefault();});$(document).on('dragover',function(e){e.stopPropagation();e.preventDefault();});$(document).on('drop',function(e){e.stopPropagation();e.preventDefault();});}});});}(window,jQuery));;(function($){$(function(){$("form.xforms-form").each(function(){var form=$(this),tmr;form.bind({XForms_Enrich:function(e){$(".xforms-control",e.args.data).focus(function(){$(this).closest(".xforms-cc").addClass("focus");}).blur(function(){$(this).closest(".xforms-cc").removeClass("focus");});$("a.jump-to-page").click(function(){var el=document.getElementById($(this).attr("data-elementid"));if(el)el.click();return false;});$("a.jump-to-page").focus(function(){$(this).closest(".xforms-cc").addClass("focus");}).blur(function(){$(this).closest(".xforms-cc").removeClass("focus");});$("button.xforms-trigger.confirm",e.args.data).click(function(){if(!confirm($(this).attr("data-message")||$.scf.locale.getString("SMS.MGR.GENERAL.ARE_YOU_SURE"))){return false;}});if($.fn.passwordStrength){$("input[type=password].check-password-strength",e.args.data).passwordStrength();}},XForms_Error:function(e){if(e.isDefaultPrevented()){return;}
$("<div title='XForms Error'>"+e.args.msg+"</div>").dialog({dialogClass:"xforms-message modal",buttons:{"OK":function(){$(this).dialog("close");}},modal:true});return true;},XForms_Unload:function(e){if(e.args.xfOpts.host==="xfwb10"){var opt;try{opt=window.external.raiseEvent("getOption","WarnWhenLeavingChangedForm");}catch(ex){}
if(!opt){return;}}
if(e.args.xfOpts.xco.unloadWarning===""){return;}
return typeof(e.args.xfOpts.xco.unloadWarning)==="undefined"?"You have started filling out this Form.\r\nYour changes will be lost if you navigate away.":e.args.xfOpts.xco.unloadWarning;},XForms_ReadyStateChange:function(e){var busyDiv,elm=$(e.args.origin);if(!e.args.ready){if(elm.is("form, .xforms-block-ui")){$.xforms.blockUI(elm);}else if(elm.length){elm.data("ready",false);tmr=setTimeout(function(){if(elm.data("ready")===false){busyDiv=$("<span class='xforms-ui-busy'></span>");elm.after(busyDiv);}},400);}}else{$.xforms.unblockUI(elm);}}});});});})(jQuery);;(function(W,$){W.console=W.console||{log:function(){}};String.prototype.endsWith=function(suffix){return this.indexOf(suffix,this.length-suffix.length)!==-1;};var XFORMS_ERROR_BASE=216770,DEBUG=1,body;$.xhrPool=[];$.xhrPool.abortAll=function(){$(this).each(function(idx,jqXHR){jqXHR.abort();});};$.ajaxSetup({beforeSend:function(jqXHR){$.xhrPool.push(jqXHR);}});$(document).ajaxComplete(function(e,x,o){$.xhrPool.pop();});$.extend({xforms:{htmlEncode:function(value){return $('<div/>').text(value).html();},htmlDecode:function(value){return $('<div/>').html(value).text();},getProperty:function(el,prop){el=$(el);var form=$(el.get(0).form);var m=form.data("meta")||{};m=m[el.attr("id")]||{};return m[prop];},getOuterHTML:function(o){if(o[0].outerHTML){return o[0].outerHTML;}
var content=o.wrap('<div></div>').parent().html();o.unwrap();return content;},validState:function(o,valid){cc=o.closest(".xforms-cc");if(typeof(valid)==='undefined'){valid=!cc.hasClass("xforms-invalid");}
if(valid){cc.addClass("xforms-valid").removeClass("xforms-invalid");}else{cc.addClass("xforms-invalid").removeClass("xforms-valid");}},resizeOverlay:function(){$('.xforms-ui-overlay').css({width:$(W).width(),height:$(W).height()});},keyBlocker:function(ev){ev.preventDefault();W.console.log("Key blocked: "+ev.which);},blockUI:function(elm,opts){if(!$.xforms.uiOverlayResize){$(W).bind({resize:$.xforms.resizeOverlay,scroll:$.xforms.resizeOverlay});$.xforms.uiOverlayResize=true;}
$(W).bind({keydown:$.xforms.keyBlocker});var options={message:"Busy...",wait:300,opacity:0.5,duration:500,mode:"lighten"};$.extend(options,opts);$(".xforms-ui-overlay, .xforms-ui-busy").remove();if(elm){elm=$(elm);elm.data("ready",false);clearTimeout(elm.data("tmr"));}
$("<div class='xforms-ui-overlay'></div>").css({background:(options.mode==="lighten")?"#fff":"#000",zIndex:99999,display:'block',opacity:0,top:$(W).scrollTop(),left:$(W).scrollLeft(),width:$(W).width(),height:$(W).height()}).appendTo("body");if(elm){var tmr=setTimeout(function(){$(".xforms-ui-overlay").animate({opacity:options.opacity},options.duration,null,function(){if($(".xforms-ui-overlay").length>0&&options.message){$("<span class='xforms-ui-busy full'>"+options.message+"</span>").css({display:"none"}).appendTo(".xforms-ui-overlay").fadeIn(200,function(){setTimeout(function(){if($(".xforms-ui-overlay").length===0){$(".xforms-ui-busy.full").remove();}},5000);});}});},options.wait);elm.data("tmr",tmr);}},unblockUI:function(elm){$(W).unbind({keydown:$.xforms.keyBlocker});if(elm){elm=$(elm);elm.data("ready",true);var tmr=elm.data("tmr");clearTimeout(tmr);}
var rem=function(){$(".xforms-ui-overlay, .xforms-ui-busy").fadeOut(100,function(){$(".xforms-ui-overlay, .xforms-ui-busy").remove();});};rem();setTimeout(rem,210);},diff:{Unknown:0,ValueChange:1,StateChange:2,Show:4,Hide:8,AddedChild:16,RemovedChild:32,ControlChange:64,CompleteForm:128},raiseEvent:function(form,opts,name,args){var e=$.Event("XForms_"+name);e.args=args||{};e.args.xfOpts=opts;form.trigger(e);if(e.result){W.console.log("XForms_"+name+" event handled by external code");}
return e.result;},hotTracking:false}});$.fn.xform=function(opts){var form=$(this);body=$("body");var xfOpts={dev:{name:"unknown",ver:"1.0",tpl:"default"},meta:{},methods:{toJSON:(typeof($.toJSON)==="function")?$.toJSON:function(s){throw new Error(XFORMS_ERROR_BASE+20,"No toJSON method attached.");},transport:null},callback:{id:null},state:{},xco:{}};$.extend(xfOpts,opts);$("body, form.xforms-form").removeClass("noscript").addClass("script");form.data("meta",xfOpts.meta);if(!xfOpts.callback.id&&xfOpts.callbackId){xfOpts.callback.id=xfOpts.callbackId;}
return this.each(function(){var formId=form.attr("id")||"xform1";xfOpts.state={guid:form.find("input[name=XForms-Context]").val(),id:formId,url:document.location.href,ace:xfOpts.ace||[],changeCount:xfOpts.chc,debug:$('#'+formId+"-debug"),timers:{incremental:{handle:null,interval:xfOpts.xco.incrementalDelay||200},change:{handle:null,interval:200},autoSave:{handle:null,interval:xfOpts.xco.autoSave||0}},controls:{focus:null,last:null,current:null}};form.bind({PersistState:function(e,args){args=args||{};args.type="persist-state";controlChanged(null,null,args);xfOpts.suppressDirtyCheck=true;return true;},SuppressDirtyCheck:function(e,args){xfOpts.suppressDirtyCheck=true;},SetOptions:function(e,args){$.extend(xfOpts,args);},SetValue:function(e,args){if(!args||!args.control||!args.control.length||typeof(args.value)==='undefined'){throw new Error("Must pass control and value");}
args.type="change";args.mode="setvalue";args.values={};args.values[args.control.attr("name")]=args.value;controlChanged(null,args.control,args);}});form.bind("DispatchCustomEvent",function(e,args){var readyHandler=typeof(args.ready)==="function"?args.ready:null;if(readyHandler){args.ready=null;}
ajax({id:xfOpts.state.guid,type:"dispatch-custom-event",userValues:args},function(x){ajaxReady(x,{});if(readyHandler){readyHandler(e);}});});$(W).bind('beforeunload',function(){W.documentUnloading=true;var currentFocus=xfOpts.state.controls.triggerFocus||xfOpts.state.controls.focus;W.console.log("Beforeunload triggered, currentFocus: "+currentFocus);if(xfOpts.state.changeCount>0&&!xfOpts.suppressDirtyCheck){W.console.log("Changes in form and suppressDirtyCheck is off. Focus: "+currentFocus);if(currentFocus&&$("#"+currentFocus).closest(".app-continue, .ignore-dirty").length){W.console.log("Focus in .app-continue or .ignore-dirty, so unload warning is suppressed.");return;}
return raiseEvent("Unload");}});form.addClass(xfOpts.dev.name).addClass(xfOpts.dev.name+"_"+xfOpts.dev.ver);raiseEvent("Enrich",{data:form});setTimeout(function(){raiseEvent("Modified");raiseEvent("Dirty",{value:xfOpts.state.changeCount>0,onload:true});},100);function processMessage(text,type,id,fromAjax){var obj=null;if(text&&text.substr(0,1)==="{"&&text.substr(text.length-1,1)==="}"){text=eval('('+text+')');}
if(raiseEvent("Message",{type:type,data:text,id:id,fromAjax:fromAjax})){return;}
switch(type){case"ephemeral":if(raiseEvent("EphemeralMessage",{data:text,id:id})){return;}
W.console.log(text+" ("+type+")");break;case"modal":if(raiseEvent("ModalMessage",{data:text,id:id})){return;}
showModalMessage(text);break;case"modeless":if(raiseEvent("ModelessMessage",{data:text,id:id})){return;}
W.console.log(text+" ("+type+")");break;case"setfocus":W.console.log("SetFocus message: "+text);if(xfOpts.state.controls.focus){setTimeout(function(){dispatchEvent(null,"DOMFocusOut",$("#"+xfOpts.state.controls.focus));},fromAjax?1:200);}
xfOpts.state.controls.focus=null;var f=$("#"+text);if(f.is(".xforms-check-group")){f=f.find("input").first();}
if(!f.hasClass("xforms-control")){f=f.find(".xforms-control:first");}
if(f.length){f.focus();xfOpts.state.controls.focus=f.attr("id");xfOpts.state.controls.focusSet=true;}else{W.console.log("Did not find "+text+" to set focus");}
break;case"load":W.console.log("Load message "+text);var p=text.indexOf(":");if(p!==-1){var cmd=text.substr(0,p),url=text.substr(p+1);if(cmd==="replace"){xfOpts.suppressDirtyCheck=true;if(url=='.')
document.location.reload(true);else
document.location.href=url;}else{W.open(url);}}
break;case"replacecontext":xfOpts.suppressDirtyCheck=true;var ctxUrl=xfOpts.state.url;document.location.href=ctxUrl+(ctxUrl.indexOf("?")==-1?"?":"&")+"newcontext="+text;break;default:W.console.log(text+" (message type: "+type+")");break;}}
function processMessages(data,msgArray){if(typeof(msgArray)!=='undefined'){data=null;}
var e;try{if(msgArray&&msgArray.length){for(e in msgArray){if(msgArray.hasOwnProperty(e)){var msg=msgArray[e];processMessage(msg.txt,msg.type,msg.id,true);}}}else if(data&&data.length){data.find(".xforms-message").each(function(){var el=$(this),text=el.html(),id=el.attr("data-id")||el.attr("rel");if(el.hasClass("modal")){processMessage(text,"modal",id);}else if(el.hasClass("ephemeral")){processMessage(text,"ephemeral",id);}else if(el.hasClass("modeless")){processMessage(text,"modeless",id);}else if(el.hasClass("setfocus")){processMessage(text,"setfocus",id);}else if(el.hasClass("load")){processMessage(text,"load",id);}else{processMessage(text,el.attr("class").replace("xforms-message ",""),id);}});}}catch(ex){if(ex.number===-2147467259||!ex.message){return;}
throw ex;}}
setTimeout(function(){processMessages(form);},10);function resetAutoSave(){if(xfOpts.state.timers.autoSave.interval>0){xfOpts.state.timers.autoSave.handle=setTimeout(function(){autoSave();},xfOpts.state.timers.autoSave.interval);}}
resetAutoSave();function autoSave(){controlChanged(null,null,{type:"autosave"});}
function handleUIStateException(obj){if(obj.error.type==="Smartsite.XForms.XFormsInvalidUIStateException"){if(form.data("aborting")){return true;}
form.data("aborting",true);readyChange(false,form);$.xhrPool.abortAll();ajax({id:xfOpts.state.guid,type:"none",userValues:{}},function(x){ajaxReady(x,{});readyChange(true,form);form.data("aborting",false);});return true;}}
function ajax(data,handler,origin){W.console.log("Starting ajax call...");if(origin&&!origin.is("button")){xfOpts.state.callbacks=(xfOpts.state.callbacks||0)+1;}
readyChange(false,origin);if(data.userValues!==null){data.userValues.x_requestId=xfOpts.x_requestId;}
var formData={ix:{src:xfOpts.callback.id},xform10:data};if(xfOpts.methods.transport){xfOpts.methods.transport(formData,handler);}else{var ajaxOptions={ixOptions:{action:"xforms-update"},url:xfOpts.state.url,dataType:"text",cache:false,contentType:"application/json",type:"POST",timeout:20000,data:xfOpts.methods.toJSON(formData),error:function(x,textStatus,errorThrown){if(W.documentUnloading){W.console.log("Ajax error response ignored: document is unloading");return;}
readyChange(true,origin);var msg=x.statusText||"Unknown server error";if(textStatus+"/"+errorThrown==="abort/abort"){W.console.log("Ajax call aborted");}else{raiseError({msg:msg,type:textStatus,serverResponse:x.responseText},26);}},success:function(x,status,xhr){if((xhr.getResponseHeader("content-type")||"").indexOf("application/json")!=0){document.location.reload();return;}
if(x!==null){try{if(x.length===0){return;}
obj=eval("("+x+")");}catch(ex){var e,exdata='';for(e in ex){if(ex.hasOwnProperty(e)){exdata+='\r\n'+e+' = '+ex[e];}}
throw new Error(XFORMS_ERROR_BASE+1,"Invalid response JSON: \r\n"+exdata);}
try{if(typeof(obj.error)==='object'){readyChange(true,origin);if(!handleUIStateException(obj)&&!raiseEvent("Error",{msg:obj.error.msg,errorNumber:obj.error.number,type:obj.error.type,exception:new Error(XFORMS_ERROR_BASE+25,obj.error.msg)})){showModalMessage(obj.error.msg,"XForms Error");}}else{handler(obj);readyChange(true,origin);}}catch(y){}}}};return $.ajax(ajaxOptions);}}
function readyChange(ready,origin){if(origin){$(origin).data("x-busy",ready===true);}
return raiseEvent("ReadyStateChange",{ready:typeof(ready)==="undefined"?true:ready,origin:origin});}
function raiseEvent(name,args){return $.xforms.raiseEvent(form,xfOpts,name,args);}
function raiseError(error,options){if(typeof(error)!=='object'){error={msg:error};}
if(typeof(options)==="object"){$.extend(error,options);}
if(!raiseEvent("Error",error)){showModalMessage(error.msg,"XForms Error");}}
function showModalMessage(txt,caption){if(caption){txt=caption+"\r\n"+txt;}
alert(txt);}
function updateStateVar(id){xfOpts.x_requestId=id;xfOpts.state.guid=xfOpts.state.guid.split("|")[0]+"|"+id;var si=form.find("input[name=XForms-Context]");si.val(xfOpts.state.guid);}
function ajaxReady(data,opts){xfOpts.state.controls.current=null;xfOpts.state.controls.triggerFocus=null;var ctl,htmlChange=false,o,i,v,c,img,newForm=null,formHtml;xfOpts.state.controls.active=null;readyChange(true,opts.triggeredBy);if(data){updateStateVar(data.x_requestId);xfOpts.state.ace=data.ace||xfOpts.state.ace;if(xfOpts.state.changeCount!==data.chc){raiseEvent("Dirty",{value:data.chc>0});}
xfOpts.state.changeCount=data.chc;if(data.meta){form.data("meta",data.meta);}
if(typeof(data.error)==='object'){if(!handleUIStateException(data)){raiseError(data.error,41,{errorNumber:data.error.number});}}else if(data.submitResponse){$("html").html($(data.submitResponse));return;}else if(data.html){htmlChange=true;newForm=$(data.html).unwrap();}
W.console.log("Evaluating response Json: data.controls "+typeof(data.controls)+", data.html: "+typeof(data.html)+", data.blocks: "+typeof(data.blocks)+", isUpload: "+opts.isUpload);if(data.controls){for(o in data.controls){if(data.controls.hasOwnProperty(o)){ctl=$('#'+o);W.console.log("Control update for #"+o);v=data.controls[o];skip=(opts.incremental&&opts.triggeredBy.attr('id')===o);if(!skip){if(ctl.hasClass("xforms-output")){img=ctl.find("img");if(img.length===1){img.attr("src",v);}else{ctl.html(v);}}else{var replacedHtml=false;if(newForm){data.blocks=data.blocks||{};if(!data.blocks[o]){data.blocks[o]={t:$.xforms.diff.ControlChange};}}
if(!replacedHtml){setControlValue(ctl,v);}}}}}}
if(htmlChange&&newForm){if(data.messages&&data.messages.length!=0){for(var m=0;m<data.messages.length;m++){if(data.messages[m].type==="load"){processMessages(data.html,data.messages);return;}}}
htmlChange=true;formHtml=newForm.html();data.replaced=[];if(data.blocks&&!raiseEvent("EffectStart",{data:data})){for(c in data.blocks){if(data.blocks.hasOwnProperty(c)){data.blocks[c].useParent=($('#'+c).length===0);}}
for(i=1;i<=2;i++){var doParents=(i===1);for(c in data.blocks){if(doParents!==data.blocks[c].useParent){continue;}
var ctlNew,name=c,toParent=false;if(data.blocks.hasOwnProperty(name)){var ctlOld=$('#'+name),mode=data.blocks[name].t;if(data.blocks[name].useParent){name=data.blocks[name].p;if(!name){W.console.log("Skipping "+name);continue;}
ctlOld=$("#"+name);}
evtProps={mode:mode,data:data,triggeredBy:opts.triggeredBy};W.console.log("Block handling for #"+name+", mode: "+mode+", count: "+ctlOld.length+(toParent?" (used parent)":""));if(ctlOld.length===1){if(mode&$.xforms.diff.StateChange){effect(data,"StateChange",ctlOld,true,evtProps);}
if(mode&$.xforms.diff.Hide){if(doParents)continue;var cc=ctlOld.is(".xforms-trigger")?ctlOld:ctlOld.closest(".xforms-cc");W.console.log("Hide "+(ctlOld.attr('id')||"element"));if(cc.length===1){effect(data,"Remove",cc,null,evtProps);}else{effect(data,"Remove",ctlOld,null,evtProps);}
data.replaced.push(name);}else if(mode&$.xforms.diff.Show){ctlNew=newForm.find('#'+name).add(newForm.filter('#'+name));if(doParents){W.console.log("Replace parent to show "+c);effect(data,"Replace",ctlOld,ctlNew,evtProps);}else{continue;}
data.replaced.push(name);}else if(mode&$.xforms.diff.ControlChange){if(toParent){W.console.log("ControlChange #"+name+" (parent)");ctlNew=newForm.find('#'+name).add(newForm.filter('#'+name));evtProps.toParent=true;effect(data,"Replace",ctlOld,ctlNew,evtProps);}else{if(ctlOld.closest(".xforms-cc").length){W.console.log("ControlChange #"+name+" (cc)");ctlNew=newForm.find('#'+name).add(newForm.filter('#'+name)).closest(".xforms-cc");effect(data,"Replace",ctlOld.closest(".xforms-cc"),ctlNew,evtProps);}else{ctlNew=newForm.find('#'+name).add(newForm.filter('#'+name));evtProps.toParent=!ctlOld.is(".xforms-control, .xforms-uc");W.console.log("ControlChange #"+name+" (other, toParent="+evtProps.toParent+", old: "+ctlOld.length+", new: "+ctlNew.length+")");effect(data,"Replace",ctlOld,ctlNew,evtProps);}}
data.replaced.push(name);}else if((mode&$.xforms.diff.RemovedChild)!==0){effect(data,"Remove",ctlOld,null,evtProps);data.replaced.push(name);}else if(!(mode&$.xforms.diff.ValueChange)){var isReplacedCC=false;if(ctlOld.is(".xforms-control, .xforms-output")){ctlNew=newForm.find('#'+name).add(newForm.filter('#'+name)).closest(".xforms-cc");oldCC=ctlOld.closest(".xforms-cc");if(ctlNew.length&&oldCC.length){effect(data,"Replace",oldCC,ctlNew,evtProps);data.replaced.push(name);isReplacedCC=true;}}
if(!isReplacedCC){ctlNew=newForm.find('#'+name).add(newForm.filter('#'+name));effect(data,"Replace",ctlOld,ctlNew,evtProps);data.replaced.push(name);}}}else if(!(mode&$.xforms.diff.Hide)&&name.indexOf("lbl")===-1){W.console.log("ERROR: found "+ctlOld.length+" occurrences of '"+name+"'. EXITING!","error");data.replaceError=true;xfOpts.state.controls.focus=$(":focus").attr("id");xfOpts.state.controls.focusSet=false;break;}}}}
raiseEvent("EffectEnd",{data:data});}
if(!data.blocks||(data.blocks&&data.replaced.length===0)||data.replaceError){W.console.log("Full Form HTML replaced: \r\n"+(DEBUG>1?formHtml:formHtml.length+" bytes"));var evtProps={mode:$.xforms.diff.CompleteForm,data:data,triggeredBy:opts.triggeredBy,html:formHtml};effect(data,"Replace",form,newForm,evtProps);}}
if(opts.isUpload){$("img.xforms-output").each(function(){W.console.log("Refresh "+$(this).attr("src"));$(this).attr("src",$(this).attr("src"));});}
for(o in data.state){if(data.state.hasOwnProperty(o)){W.console.log("Set modified/valid state for "+o);ctl=$('#'+o);var state=data.state[o],changed=state.substr(state.indexOf("c")+1,1)==='1',valid=state.substr(state.indexOf("v")+1,1)==='1';if(ctl.length===0){ctl=$("label[for="+o+"]");}
effect(data,"statechange",ctl,valid,{mode:null,data:data,triggeredBy:opts.triggeredBy});if(changed&&!ctl.closest(".xforms-cc").hasClass("xforms-modified")){ctl.closest(".xforms-cc").addClass("xforms-modified");}else if(ctl.closest(".xforms-cc").hasClass("xforms-modified")){ctl.closest(".xforms-cc").removeClass("xforms-modified");}}}
raiseEvent("Modified",{dynamic:true,htmlChange:htmlChange,data:data,triggeredBy:opts.triggeredBy});if(xfOpts.state.debug){$(xfOpts.state.debug).html("");}
if(data.debug&&xfOpts.state.debug){$(xfOpts.state.debug).html($(data.debug).unwrap().html());}
processMessages(data.html,data.messages||null);if(xfOpts.state.controls.focus&&!xfOpts.state.controls.focusSet){var f=$('#'+xfOpts.state.controls.focus);if(f.length===1){setTimeout(function(){if(!f.is(":focus")){W.console.log("Setting focus to "+xfOpts.state.controls.focus);try{setCaretToPos(f.focus().get(0),100000);}
catch(e){}}},10);}}}}
function effect(data,type,obj1,obj2,settings){type=type.toLowerCase();var id=obj1.attr('id'),exists=$.inArray(id,data.replaced);if(exists!==-1){W.console.log("Skipping effect for "+id+", because this element is a duplicate...");return;}
var s,props={type:type,object1:obj1,object2:obj2};if(type==="replace"||type==="remove"){raiseEvent("Unenrich",{data:obj1});props.ready=function(){try{raiseEvent("Enrich",{data:obj2});}catch(x){}};}
$.extend(props,settings);if(!raiseEvent("Effect",props)){switch(type){case"remove":obj1.remove();break;case"replace":if(obj1.length===0&&obj2.length===0){W.console.log("Exiting effect, found "+obj1.length+", "+obj2.length);return;}
if(props.mode===$.xforms.diff.CompleteForm){W.console.log("Replace complete form html.");raiseEvent("Unenrich",{data:form});form.html(data.html);raiseEvent("Enrich",{data:form});}else{if(obj1.length){raiseEvent("Unenrich",{data:obj1});var html2=obj2.html();if(html2){W.console.log(obj1.attr('id')+" set to "+(DEBUG>1?html2:html2.length+" bytes"));obj1.html(html2);}else{W.console.log(obj1.attr('id')+" cleared");obj1.html("");}
obj1.attr("class",obj2.attr("class"));if(obj2.attr("disabled"))
obj1.attr("disabled",obj2.attr("disabled"));else
obj1.removeAttr("disabled");raiseEvent("Enrich",{data:obj1});}else{W.console.log("No element obj1");}}
break;case"statechange":W.console.log("Setting valid state of "+obj1.attr('id')+" to "+obj2);$.xforms.validState(obj1,obj2);break;}}}
function setControlValue(ctl,v,defaultValue){var list,i,selected,parts;if(typeof(ctl.data("set-value"))=='function'){if(ctl.data("set-value")(v,defaultValue)){return;}}
if(ctl.hasClass("xforms-select")){var isBitField=ctl.hasClass("xforms-cap-bit-field");parts=v.split(" ");if(!ctl.is("select")){list=ctl.find("input");list.each(function(){selected=false;if(isBitField){selected=((this.value&v)!==0);}else{for(i=0;i<parts.length;i++){if(this.value===parts[i]){selected=true;break;}}}
if(defaultValue){var checked=this.checked;this.defaultChecked=selected;this.checked=checked;}else{this.checked=selected;}});return;}}
if(defaultValue===true){ctl.prop("defaultValue",v);}else{ctl.val(v);if(ctl.hasClass("xforms-builtin-type-boolean")){ctl.prop("checked",JSON.parse(v));}
ctl.data("currentValue",v);if(typeof(defaulValue)==="undefined"){setControlValue(ctl,v,true);}}}
function setSelectionRange(input,selectionStart,selectionEnd){try{if(input.setSelectionRange){input.focus();input.setSelectionRange(selectionStart,selectionEnd);}else if(input.createTextRange){var range=input.createTextRange();range.collapse(true);range.moveEnd('character',selectionEnd);range.moveStart('character',selectionStart);range.select();}}catch(e){}}
function setCaretToPos(input,pos){setSelectionRange(input,pos,pos);}
function getCheckboxListValues(ctl,defaultValues){var s="",cbs;if(!defaultValues){cbs=ctl.closest("div.xforms-control.xforms-check-group").find(":checked");cbs.each(function(){s+=$(this).val()+" ";});}else{cbs=ctl.closest("div.xforms-control.xforms-check-group").find("input");cbs.each(function(){$(this).prop("defaultChecked");if($(this).prop("defaultChecked")){s+=$(this).val()+" ";}});}
if(s.substr(s.length-1,1)===" "){s=s.substr(0,s.length-1);}
return s;}
function doUpload(ctl,o,doCallback){var cancelled=false;W.console.log("Starting upload on "+ctl.attr("id"));ctl.data("upf-id",parseInt("0"+ctl.data("upf-id"),0)+1);var fName="upload"+ctl.data("upf-id"),upi=$("<span class='xforms-upload-progress'><input name='__CSE' type='hidden' value='1' /><button class='xforms-upload-cancel'>x</button>&nbsp;</span>"),upf=$('<iframe id="'+fName+'" name="'+fName+'"></iframe>'),txt,err,upfBody,ctx;if(ctl.closest(".fakeupload").length){ctl.closest(".fakeupload").after(upi);}else{if(ctl.next().is("div.drag-drop-upload"))
ctl.next().after(upi);else
ctl.after(upi);}
var finish=function(abort){cancelled=abort===true;upi.fadeOut(200,function(){upi.remove();upf.remove();raiseEvent(abort?"UploadAborted":"UploadReady",{control:ctl});});};upi.find(".xforms-upload-cancel").click(function(){finish(true);});raiseEvent("UploadStarting",{control:ctl,abort:function(){finish(true);},frame:upf});upf.hide().appendTo(form).load(function(event){W.console.log("Upload on "+ctl.attr("id")+" ready");if(!cancelled){upfBody=upf.contents().find("body");err=upf.contents().find(".xforms-error");if(err.length){raiseError({msg:err.text(),type:"UploadException"},28);}else{ctx=upfBody.find("input[name=XForms-Context]");if(ctx.length===0){var html=upfBody.html();W.console.log("Error in upload:\r\n"+html);if(html.indexOf('Maximum request length exceeded')===-1&&html.indexOf('content length exceeds the configured value')===-1){raiseError({msg:"An error occurred while uploading a file.",type:"UploadException"},37);}else{raiseError({msg:"The uploaded file exceeds the maximum allowed file size.",type:"UploadException"},37);}}else{W.console.log("Processing upload on "+ctl.attr("id")+"...");doCallback({extraCallback:fixUploadControlChange,isUpload:true});}}}else{doCallback({extraCallback:fixUploadControlChange,isUpload:true,uploadAborted:true});}
finish();});form.attr("target",fName);form.get(0).submit();}
function getModifiedValues(){var o={},n=0,list=[],change;form.find(".xforms-control:not(button, submit, input[type=file])").each(function(){change=getControlChange($(this));if($(this).closest(".xforms-hide").length===0&&change.dirty){n++;list.push(change.id);o[change.id]=change.value;}});W.console.log(n+" control updates to send to server: "+list.join(", "));return o;}
function getControlChange(ctl){var o={id:ctl.attr("id"),value:getValue(ctl),defaultValue:getDefaultValue(ctl)};o.dirty=o.value!=o.defaultValue;return o;}
function getDefaultValue(ctl){var data;if(ctl.closest("div").is(".xforms-check-group")){data=getCheckboxListValues(ctl,true);}else{if(ctl.is("select")&&ctl.prop("defaultValue")==null){data=ctl.find("option").map(function(){if($(this).prop('defaultSelected')===true){return this;}}).val();}else{data=ctl.prop("defaultValue");}
if(ctl.hasClass("xforms-builtin-type-boolean")){data=ctl.prop("defaultChecked")==="checked"?"true":"false";}else if($.isArray(data)){data=data.join(" ");}
return data;}}
function setDefaultValues(o){var ctl,a;for(a in o){if(o.hasOwnProperty(a)&&a!=="x_requestId"){ctl=$("#"+a);if(ctl.length){W.console.log("Resetting default value for "+a);setControlValue(ctl,o[a],true);}}}}
function getValue(ctl){var data;if(ctl.closest("div").is(".xforms-check-group")){data=getCheckboxListValues(ctl);}else{data=ctl.val();if(ctl.hasClass("xforms-builtin-type-boolean")){data=ctl.is(":checked")?"true":"false";}else if($.isArray(data)){data=data.join(" ");}
return data;}}
function controlChanged(e,ctl,opts){if(xfOpts.state.pendingUpload)
return;var ctlId;if(ctl&&ctl.length){ctl.data("processing",true);ctlId=ctl.attr("name");if(xfOpts.state.controls.triggerFocus){clearTimeout(xfOpts.state.timers.change.handle);xfOpts.state.controls.current={name:ctlId,value:ctl.val()};return;}}
opts=opts||{type:"change"};W.console.log("Ajax call for controlChanged (#"+ctlId+") starting. Type: "+opts.type+", evt: "+(e?e.type:"null"));var doCallback=function(options){$.extend(opts,options);var data={id:xfOpts.state.guid,type:opts.type,userValues:o};if(opts.incremental){data.incremental=true;}
ajax(data,function(data,result,jqXHR){xfOpts.state.pendingUpload=false;if(ctl&&ctl.length){ctl.data("processing",false);}
W.console.log("Ajax call for controlChanged (#"+ctlId+") ready. Type: "+opts.type+", evt: "+(e?e.type:"null")+", caller: "+controlChanged.caller);if(data!==null){opts.triggeredBy=ctl;ajaxReady(data,opts);if(typeof(extraCallback)==="function"){W.console.log("Calling extra callback");extraCallback();}
if(typeof(opts.ready)==="function"){opts.ready({xfOpts:xfOpts});}
for(var updatedControl in data.controls){delete o[updatedControl];}
setDefaultValues(o);resetAutoSave();}},ctl);};var o;if(opts.mode==="setvalue"){o=opts.values;}else{o=getModifiedValues();if(ctl&&ctl.length){if(ctl.closest("div").is(".xforms-check-group")){o[ctlId]=getCheckboxListValues(ctl);ctl=ctl.closest("div");}else{var data;ctlId=ctl.attr("id");if(ctl.attr("type")==="file"&&(ctl.prop("ddupload_completed")!==true)){xfOpts.state.pendingUpload=true;doUpload(ctl,o,doCallback);return;}
data=ctl.val();if(ctl.hasClass("xforms-builtin-type-boolean")){data=ctl.is(":checked")?"true":"false";}
if($.isArray(data)){data=data.join(" ");}
o[ctlId]=data;}
ctl.data("currentValue",o[ctlId]);}}
doCallback();}
function fixUploadControlChange(){$("input.xforms-upload.xforms-incremental").change(function(e){$(e.target).blur();});}
var onChange=function(e,force){var ctl=e.target?$(e.target):e,id=ctl.attr("id"),isIncremental=ctl.hasClass("xforms-incremental");if(ctl.data("dispatching")){return;}
if(ctl.closest("div").is(".xforms-hide")){return;}
var isSelect=!ctl.is("input[type=text]")&&(ctl.is(".xforms-select, .xforms-select1, div.xforms-select1 input[type=radio], div.xforms-select input[type=checkbox]"));var isSelectGroup=ctl.is("div.xforms-select1 input[type=radio], div.xforms-select input[type=checkbox]");if(isSelectGroup){controlChanged(e,ctl);return;}else if(isSelect||ctl.hasClass("xforms-upload")){if(isIncremental&&(ctl.is("select")||ctl.hasClass("xforms-upload")||isSelectGroup)){force=true;}
if(!force){if(!isIncremental){xfOpts.state.buf={id:id,value:ctl.val()};W.console.log("Change buffered for "+xfOpts.state.buf.id+":"+xfOpts.state.buf.value);if(isSelect&&(xfOpts.state.ace!==null&&(xfOpts.state.ace.Select||xfOpts.state.ace.Deselect))){var array1=xfOpts.state.ace.Select,array2=xfOpts.state.ace.Deselect;var cName=id.substr(formId.length+1);if($.inArray(cName,array1)!==-1||$.inArray(cName,array2)!==-1){W.console.log("Send select/deselect: "+ctl.val());controlChanged(e,ctl,{type:"select"});}}}}else{controlChanged(e,ctl);}
return;}
clearTimeout(xfOpts.state.timers.change.handle);xfOpts.state.controls.current=null;if(ctl.hasClass('xforms-control')&&ctl.attr("x-incremental")!=="1"){var v=null;if(!ctl.hasClass("xforms-upload")){v=ctl.val();if(ctl.hasClass("xforms-check-group")){v=getCheckboxListValues(ctl);}
xfOpts.state.controls.current={name:ctl.attr("name"),value:v};}
xfOpts.state.timers.change.handle=setTimeout(function(){controlChanged(null,ctl);},xfOpts.state.timers.change.interval||50);}};function dispatchEvent(e,xev,ctl){if(xfOpts.state.ace[xev]){var id=ctl.attr('id');if(!id){return;}
var array=xfOpts.state.ace[xev];var cName=id.substr(formId.length+1);if($.inArray(cName,array)!==-1){W.console.log(id+" is in array for "+xev);ctl.data("dispatching",xev);controlChanged(e,ctl,{type:xev,ready:function(){ctl.data("dispatching",null);}});}}}
function isDOMActivateEnabled(ctl){if(ctl.is("input")&&(xfOpts.state.ace!==null&&xfOpts.state.ace.DOMActivate)){var cName=ctl.attr("id").substr(formId.length+1);return($.inArray(cName,xfOpts.state.ace.DOMActivate)!==-1);}
return false;}
function testChangeBuffer(e,msg){if(!xfOpts.state.controls.active){return;}
if(xfOpts.state.buf){W.console.log("Processing buffered change in "+xfOpts.state.buf.id+": "+xfOpts.state.buf.value+" ("+msg+")");var old=$("#"+xfOpts.state.buf.id);controlChanged(e,old);xfOpts.state.buf=null;}}
form.on("focusin",".xforms-cc *:not('button.xforms-trigger')",function(e){var ctl=$(e.target).closest(".xforms-uc, .xforms-cc").find(".xforms-control");raiseEvent("SelectControl",{control:ctl});});function focusIn(e){if(e.target.nodeName==="IFRAME"){return;}
var ctl=$(e.target);if(ctl.hasClass('xforms-incremental')){ctl.attr("x-incremental","1");}
if(xfOpts.state.controls.active===e.target){return;}
testChangeBuffer(e,"Focus set to "+e.target.tagName);xfOpts.state.controls.active=e.target;xfOpts.state.controls.last=xfOpts.state.controls.focus;xfOpts.state.controls.focus=ctl.attr("id");W.console.log("xfOpts.state.controls.focus set to "+xfOpts.state.controls.focus);dispatchEvent(e,"DOMFocusIn",ctl);}
form.bind({change:onChange,DOMFocusIn:focusIn,focusin:focusIn,focusout:function(e){var ctl=$(e.target);dispatchEvent(e,"DOMFocusOut",ctl);if(xfOpts.state.controls.active===e.target){return;}
xfOpts.state.controls.active=e.target;if(ctl.attr("x-incremental")==="1"){clearTimeout(xfOpts.state.timers.incremental.handle);ctl.attr("x-incremental",null);}else if(xfOpts.state.buf){W.console.log("Applying buffered change of "+xfOpts.state.buf.id);controlChanged(e,ctl,{incremental:true,type:"change"});xfOpts.state.buf=null;}},keyup:function(e){var ctl;var k=e.which;if(k===13){ctl=$(e.target);if(isDOMActivateEnabled(ctl)){xfOpts.state.controls.active=null;dispatchEvent(null,"DOMActivate",ctl);return true;}}
if(k===13||k===32||k===46||k>=48||k===8||k===27){ctl=$(e.target);clearTimeout(xfOpts.state.timers.incremental.handle);if(ctl.attr("x-incremental")==="1"){xfOpts.state.timers.incremental.handle=setTimeout(function(){controlChanged(e,ctl,{incremental:true,type:"change"});},xfOpts.state.timers.incremental.interval||200);}}},keydown:function(e){var ctl=$(e.target);W.console.log('Keydown in '+ctl.attr('id'));if(e.which===13){e.stopPropagation();return true;}
var k=e.which;if(k===9){if(ctl.prop("defaultValue")===ctl.val()){W.console.log("No need for handling focus-out on "+ctl.attr("id"));return;}}
xfOpts.state.lastKey=k;clearTimeout(xfOpts.state.timers.incremental.handle);if(!ctl.is("BUTTON")&&e.which===13){xfOpts.state.controls.current={name:ctl.attr("name"),value:ctl.val()};}},click:function(e){xfOpts.state.lastKey=null;if($.xforms.hotTracking===true){return;}
var ctl=$(e.target),trg=ctl.closest(".xforms-trigger, .xforms-submit");if(trg.length){ctl=trg;}
if(ctl.is('.xforms-trigger, .xforms-submit')){if(ctl.closest("[disabled=disabled]").length===0){e.stopPropagation();W.console.log("Ajax call for trigger starting. Type: "+opts.type+", evt: click");clearTimeout(xfOpts.state.timers.incremental.handle);clearTimeout(xfOpts.state.timers.change.handle);var trigger=ctl.attr("name"),values=getModifiedValues();if(xfOpts.state.controls.current){W.console.log("Adding buffered change in "+xfOpts.state.controls.current.name);values[xfOpts.state.controls.current.name]=xfOpts.state.controls.current.value;xfOpts.state.controls.current=null;}
values[trigger]=1;ajax({id:xfOpts.state.guid,trigger:trigger,userValues:values},function(x){W.console.log("Ajax call for trigger ready. Type: "+opts.type+", evt: click");ajaxReady(x,{triggeredBy:ctl,incremental:false});},ctl);}
return false;}else if(ctl.is("input[type=checkbox], input[type=radio]")){ctl.focus();}else if(ctl.is(".xforms-cc, .xforms-uc, .xforms-control")){raiseEvent("SelectControl",{control:ctl});}}});$("html").bind({mousedown:function(e){xfOpts.state.controls.triggerFocus=null;var el=$(e.target),btn=el.closest(".xforms-trigger, .xforms-submit");if(btn.length){W.console.log("Trigger focused: "+btn.attr('id'));xfOpts.state.controls.triggerFocus=btn.attr('id');}},focusin:function(e){if(xfOpts.state.lastKey===9){var last;if(xfOpts.state.controls.last){last=$("#"+xfOpts.state.controls.last);if(last.attr("x-incremental")==="1"){if(last.data("currentValue")===last.val()){clearTimeout(xfOpts.state.timers.change.handle);xfOpts.state.controls.last=null;W.console.log("Cancelled ajax call after losefocus on incremental input, because value has not changed since last call.");}else{xfOpts.state.buf={id:xfOpts.state.controls.last,value:last.val()};W.console.log("Change buffered for incremental control "+xfOpts.state.buf.id+":"+xfOpts.state.buf.value);testChangeBuffer(e);}}}
W.console.log("Tab key caused focus, so no change buffering."+" Current: "+last);xfOpts.state.lastKey=null;}
var tg=e.target;if($(tg).is(".xforms-trigger span, .xforms-submit span")){tg=$(tg).parent().get(0);}
if(!xfOpts.state.controls.active||xfOpts.state.controls.active===tg){return;}
testChangeBuffer(e);}});fixUploadControlChange();});};}(window,jQuery));;(function($){if(!$.widget)
return;$.widget("ui.combobox",{_create:function(){var self=this,select=$(this.element).next().find("select"),input=this.element,selected=select.children(":selected"),value=input.val();input.autocomplete({delay:0,minLength:0,source:function(request,response){var matcher=new RegExp($.ui.autocomplete.escapeRegex(request.term),"i");response(select.children("option").map(function(){var text=$(this).text();if(this.value&&(!request.term||matcher.test(text)))
return{label:text.replace(new RegExp("(?![^&;]+;)(?!<[^<>]*)("+
$.ui.autocomplete.escapeRegex(request.term)+")(?![^<>]*>)(?![^&;]+;)","gi"),"$1"),value:text,option:this};}));},select:function(event,ui){ui.item.option.selected=true;self._trigger("selected",event,{item:ui.item.option});$(this).change();},}).addClass("ui-widget ui-widget-content ui-corner-left");this.button=$("<button type='button'>&nbsp;</button>").attr("tabIndex",-1).insertAfter(input).button({icons:{primary:"ui-icon-triangle-1-s"},text:false}).removeClass("ui-corner-all").addClass("ui-corner-right ui-button-icon").click(function(){if(input.autocomplete("widget").is(":visible")){input.autocomplete("close");return;}
$(this).blur();input.autocomplete("search","");input.focus();});},destroy:function(){this.input.remove();this.button.remove();this.element.show();$.Widget.prototype.destroy.call(this);}});$(function(){$("form.xforms-form").bind({XForms_Enrich:function(e){$("input.xforms-control.xforms-select1.open, input.xforms-control.xforms-select.open",e.args.data).combobox();}})})})(jQuery);(function(W,$){function testPasswordStrength(passwd){var score=0;if(passwd.length<5)
{score+=3;}else if(passwd.length>4&&passwd.length<8)
{score+=6;}else if(passwd.length>7&&passwd.length<16)
{score+=12;}else if(passwd.length>15)
{score+=18;}
if(passwd.match(/[a-z]/))
{score+=1;}
if(passwd.match(/[A-Z]/))
{score+=5;}
if(passwd.match(/\d+/))
{score+=5;}
if(passwd.match(/(.*[0-9].*[0-9].*[0-9])/))
{score+=5;}
if(passwd.match(/.[!,@,#,$,%,^,&,*,?,_,~]/))
{score+=5;}
if(passwd.match(/(.*[!,@,#,$,%,^,&,*,?,_,~].*[!,@,#,$,%,^,&,*,?,_,~])/)){score+=5;}
if(passwd.match(/([a-z].*[A-Z])|([A-Z].*[a-z])/))
{score+=2;}
if(passwd.match(/([a-zA-Z])/)&&passwd.match(/([0-9])/))
{score=(score+2);}
if(passwd.match(/([a-zA-Z0-9].*[!,@,#,$,%,^,&,*,?,_,~])|([!,@,#,$,%,^,&,*,?,_,~].*[a-zA-Z0-9])/)){score+=2;}
if(score<16){return 0;}
if(score>15&&score<25){return 1;}
if(score>24&&score<35){return 2;}
if(score>34&&score<45){return 3;}
return 4;}
function set(o){o.closest(".xforms-cc").removeClass("pwd-0 pwd-1 pwd-2 pwd-3 pwd-4").addClass("pwd-"+testPasswordStrength(o.val()));}
$.fn.passwordStrength=function(options){return this.each(function(){var me=$(this);me.bind({focus:function(){set(me);},keyup:function(){set(me);},change:function(){set(me);}});});};})(window,jQuery);;(function(W,$){W.console=W.console||{log:function(){}};$.tinyMCE_defaults={setup:function(editor){}};$(function(){$("form.xforms-form").bind({XForms_Unenrich:function(e){if(typeof(tinyMCE)!=="undefined"){$("textarea.tinymce",e.args.data).each(function(){var tiny=$(this).tinymce();if(tiny)tiny.remove();});}},XForms_Enrich:function(e){$(".mceMenu").hide();$("textarea.tinymce",e.args.data).each(function(){W.console.log("Binding TinyMCE XForms Enrich...");var edit=$(this);var blockformats=edit.data("blockformats");var plugins=edit.data("plugins");var buttons=edit.data("toolbar");var style_formats=eval(edit.data("styleformats"))||[];var editorCss=edit.data("editorcss")||(document.location.protocol+"//"+document.location.host+shell.mgrResUrl+"/css/content-editor.css");edit.tinymce({readonly:edit.is(":disabled"),script_url:shell.mgrResUrl+"/tinymce/tinymce.min.js",theme:"modern",plugins:plugins,content_css:editorCss,image_advtab:true,width:"100%",entity_encoding:"raw",style_formats:style_formats,toolbar1:buttons,block_formats:blockformats,language:($("html").attr("lang")||"en").substr(0,2),convert_urls:false,relative_urls:true,remove_script_host:true,document_base_url:shell.defaultSiteHostHeader,paste_as_text:true,paste_remove_styles:true,paste_strip_class_attributes:"mso",paste_block_drop:true,paste_preprocess:function(pl,o){},paste_postprocess:function(pl,o){},setup:function(editor){editor.on('focus',function(e){W.console.log("Focus set to underlying element of tinyMCE editor: "+edit.attr('data-id'));edit.trigger("focusin");});editor.on('blur',function(e){var dirty=edit.tinymce().isDirty();W.console.log("TinyMCE blur, dirty: "+dirty);if(dirty)edit.change();});editor.addButton('addlinkcontentlib',{title:translations.getString("TINYMCE_GETCONTENTLINK"),icon:'tinymce_addlink',onclick:function(){dataEditor.tinyMceCreateLink(editor,edit.attr('data-id'),'AddContentLink');}});editor.addButton('addlinkfileexplorer',{title:translations.getString("TINYMCE_GETFILELINK"),icon:'tinymce_addfilelink',onclick:function(){dataEditor.tinyMceCreateLink(editor,edit.attr('data-id'),'AddFileLink');}});editor.addButton('addimagemedialib',{title:translations.getString("TINYMCE_GETCONTENTIMAGE_MEDIALIB"),icon:'tinymce_addimage',onclick:function(){dataEditor.tinyMceAddImage(editor,edit.attr('data-id'),'OpenMediaLib');}});editor.addButton('addimagefileexplorer',{title:translations.getString("TINYMCE_GETCONTENTIMAGE_FILEEXPLORER"),icon:'tinymce_fileexplorer',onclick:function(){dataEditor.tinyMceAddImage(editor,edit.attr('data-id'),'OpenFileExplorer');}});},onchange_callback:function(e,f,g){edit.trigger("modified");edit.prop("changed",true);}});if(typeof($.tinyMCE_defaults.presetup)==="function"){W.console.log("Invoking TinyMCE custom presetup");$.tinyMCE_defaults.presetup(edit);}
W.console.log("Binding TinyMCE XForms Enrich done...");});}});});})(window,jQuery);;(function($){$(function(){$("form.xforms-form").bind({XForms_Enrich:function(e){if($.fn.datepicker){$("input.ui-date-picker",e.args.data).each(function(){var inp=$(this);if(inp.is(":disabled"))return;var dateFormat=$.xforms.getProperty(inp,'dateFormat')||'d-M-yy';dateFormat=dateFormat.replace(/m/g,'0').replace(/h/gi,'0').replace(/t/g,'').replace(/M/g,'m').replace('yyyy','yy');var clearBtn=$('<button class="ui-datepicker-clear" type="button">x</button>').click(function(){inp.val('');inp.change();return false;});inp.after(clearBtn);inp.datepicker({dateFormat:dateFormat,changeMonth:true,changeYear:true,showWeek:true,firstDay:1,yearRange:"c-100:c+15",showOn:inp.hasClass("ui-date-picker-onfocus")?"focus":"button",})});$("#ui-datepicker-div").hide();}}})})})(jQuery);;(function($){$(function(){$("form.xforms-form").bind({XForms_Enrich:function(e){if($.fn.datetimepicker){$("input.ui-datetime-picker",e.args.data).each(function(){var inp=$(this);if(inp.is(":disabled"))return;var dateFormat=$.xforms.getProperty(inp,'dateFormat')||'d-M-yy';var hr=dateFormat.match(/h/i);if(hr)hr=hr.index;else hr=dateFormat.length;timeFormat=$.trim(dateFormat.substr(hr));dateFormat=$.trim(dateFormat.substr(0,hr));dateFormat=dateFormat.replace(/M/g,'m').replace('yyyy','yy');timeFormat=timeFormat.replace(/t/g,'T');var clearBtn=$('<button class="ui-datepicker-clear" type="button">x</button>').click(function(){inp.datepicker('setDate','');inp.val('');inp.change();return false;});inp.after(clearBtn);inp.datetimepicker({showTimepicker:true,dateFormat:dateFormat,changeMonth:true,changeYear:true,showWeek:true,firstDay:1,yearRange:"c-100:c+15",showOn:inp.hasClass("ui-datetime-picker-onfocus")?"focus":"button",onSelect:function(){},timeFormat:timeFormat,currentText:translations.getString("GENERAL.NOW"),closeText:translations.getString("GENERAL.OK"),timeText:translations.getString("GENERAL.TIME"),hourText:translations.getString("GENERAL.HOUR"),minuteText:translations.getString("GENERAL.MINUTES"),})});$("#ui-datepicker-div").hide();}}})})})(jQuery);;(function($){$(function(){$("form.xforms-form").bind({XForms_ModalMessage:function(e){return showDialog(e,true,e.args.data);},XForms_ModelessMessage:function(e){return showDialog(e,false,e.args.data);},XForms_EphemeralMessage:function(e){return showTooltip(e,e.args.data,e.args.id);}});function showDialog(e,modal,data){e.args.xfOpts.dlgCount=(e.args.xfOpts.dlgCount||0)+1;$("<div title='Form message'>"+data+"</div>").dialog({dialogClass:"xforms-message "+(modal?"modal":"modeless"),buttons:{"OK":function(){$(this).dialog("close").remove();}},modal:modal,zIndex:1000-e.args.xfOpts.dlgCount});return true;}
function showTooltip(e,text,id){var d=$("<div class='xforms-message ephemeral'>"+text+"</div>");var x=e.pageX+10,y=e.pageY+10;if(id){var el=$("#"+id);x=el.offset().left+20;y=el.offset().top+el.outerHeight()+5;}
$(".xforms-message.ephemeral").remove();d.css({position:"absolute",display:"none",top:y+"px",left:x+"px",cursor:"default",zIndex:5000}).appendTo($("body")).fadeIn().click(function(){$(this).fadeOut("fast")});setTimeout(function(){d.fadeOut()},Math.min(5000,1000+text.length*50));return true;}})})(jQuery);(function(W,$){W.console=W.console||{log:function(){}};$(function(){$("form.xforms-form").bind({XForms_Unenrich:function(e){$(".xforms-sortable").each(function(){W.console.log("Unbinding xforms-sortable behavior...");try{$(this).sortable("cancel");$(this).sortable("destroy");}catch(e){};});},XForms_Enrich:function(e){$(".xforms-sortable").each(function(){W.console.log("Binding xforms-sortable behavior...");var panel=$(this),form=panel.closest("form"),els,count,cls,settings,itemSelector,context=panel.attr("data-context"),customEvent=panel.attr("data-sort-event")||"sort-fields";if(panel.is("ul, ol")){itemSelector="> li";}else{itemSelector=".xforms-rc";}
els=panel.find(itemSelector);count=els.length;cls=els.first().attr("class");settings={items:itemSelector,opacity:0.6,connectWith:panel.attr("data-sort-connect"),revert:'invalid',tolerance:"pointer",helper:'clone',zIndex:100,delay:50,placeholder:"drop-placeholder "+cls,cursor:"ns-resize",activate:function(event,ui){var h=ui.helper.height();ui.placeholder.height(h);},start:function(event,ui){var start=ui.item.prevAll().length;W.console.log("Start pos: "+start);ui.item.data('start_pos',start);ui.item.closest("form").data("drag-operation",true);},change:function(event,ui){var pos=ui.placeholder.index();W.console.log("Moving, pos: "+pos);ui.item.data('new_pos',pos);},stop:function(event,ui){var start=ui.item.data('start_pos'),stop=ui.item.data('new_pos');if(typeof(stop)==='undefined'){return;}
W.console.log("Stop event: start="+start+", stop="+stop);if(stop>count){stop=count;W.console.log("Stop event: stop>count, so stop=count: "+stop);}
if(start>=0&&stop>=0&&start!==stop){W.console.log("Firing "+customEvent+" custom event, start="+start+1+", stop="+stop+1);ui.item.closest("form").trigger("DispatchCustomEvent",{"custom-event-name":customEvent,"event-data":{from:start+1,to:stop+1,context:context}});}}};if($(this).hasClass("xforms-sortable-axis-y")){settings.axis="y";}else if($(this).hasClass("xforms-sortable-axis-x")){settings.axis="x";}
panel.sortable(settings);});}});});}(window,jQuery));
})(jQuery);