# Starter pipeline
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(afbda82c-bc14-483a-afc6-1911cca0ae53)'
    appType: 'webAppLinux'
    appName: 'HELM-OTAP-TEST'
    deployToSlotOrASE: true
    resourceGroupName: 'HELM-OTAP-TEST'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
