# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'HELM OTAP TEST Serivice connection'
    appType: 'webAppLinux'
    appName: 'HELM-SITE-TEST'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PHP|7.4'
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
