# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Add steps to build the project
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet build --configuration Release
  displayName: 'Build project'

# Publish the build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/**/bin/Release/net5.0/publish'
    artifactName: 'drop'
    publishLocation: 'Container'

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(afbda82c-bc14-483a-afc6-1911cca0ae53)'
    appType: 'webAppLinux'
    appName: 'HELM-OTAP-TEST'
    deployToSlotOrASE: true
    resourceGroupName: 'HELM-OTAP-TEST'
    slotName: 'production'
    package: '$(Pipeline.Workspace)/drop/**/*.zip'
